// Mocks generated by Mockito 5.4.4 from annotations
// in myapp/test/features/product/data/repositories/product_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:myapp/core/network/network_info.dart' as _i7;
import 'package:myapp/features/product/data/data_sources/product_local_data_source.dart'
    as _i4;
import 'package:myapp/features/product/data/models/product_model.dart' as _i2;

import '../../helpers/mocks.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductModel_0 extends _i1.SmartFake implements _i2.ProductModel {
  _FakeProductModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i3.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [ProductLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDataSource extends _i1.Mock
    implements _i4.ProductLocalDataSource {
  MockProductLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.ProductModel>> getAllProducts() => (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.ProductModel>>.value(<_i2.ProductModel>[]),
      ) as _i5.Future<List<_i2.ProductModel>>);

  @override
  _i5.Future<_i2.ProductModel> getProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getProduct,
          [id],
        ),
        returnValue: _i5.Future<_i2.ProductModel>.value(_FakeProductModel_0(
          this,
          Invocation.method(
            #getProduct,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.ProductModel>);

  @override
  _i5.Future<_i2.ProductModel> insertProduct(_i2.ProductModel? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertProduct,
          [product],
        ),
        returnValue: _i5.Future<_i2.ProductModel>.value(_FakeProductModel_0(
          this,
          Invocation.method(
            #insertProduct,
            [product],
          ),
        )),
      ) as _i5.Future<_i2.ProductModel>);

  @override
  _i5.Future<_i2.ProductModel> updateProduct(_i2.ProductModel? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [product],
        ),
        returnValue: _i5.Future<_i2.ProductModel>.value(_FakeProductModel_0(
          this,
          Invocation.method(
            #updateProduct,
            [product],
          ),
        )),
      ) as _i5.Future<_i2.ProductModel>);

  @override
  _i5.Future<String> deleteProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #deleteProduct,
            [id],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i2.ProductModel> cacheProducts(
          List<_i2.ProductModel>? products) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProducts,
          [products],
        ),
        returnValue: _i5.Future<_i2.ProductModel>.value(_FakeProductModel_0(
          this,
          Invocation.method(
            #cacheProducts,
            [products],
          ),
        )),
      ) as _i5.Future<_i2.ProductModel>);

  @override
  _i5.Future<_i2.ProductModel> cacheProduct(_i2.ProductModel? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProduct,
          [product],
        ),
        returnValue: _i5.Future<_i2.ProductModel>.value(_FakeProductModel_0(
          this,
          Invocation.method(
            #cacheProduct,
            [product],
          ),
        )),
      ) as _i5.Future<_i2.ProductModel>);

  @override
  _i5.Future<List<_i2.ProductModel>> getLastProducts() => (super.noSuchMethod(
        Invocation.method(
          #getLastProducts,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.ProductModel>>.value(<_i2.ProductModel>[]),
      ) as _i5.Future<List<_i2.ProductModel>>);

  @override
  _i5.Future<_i2.ProductModel> getCachedProduct(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedProduct,
          [id],
        ),
        returnValue: _i5.Future<_i2.ProductModel>.value(_FakeProductModel_0(
          this,
          Invocation.method(
            #getCachedProduct,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.ProductModel>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
